// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyWpf.Models;

namespace StudyWpf.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("StudyWpf.Models.TestModel", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("SheetId");

                    b.Property<string>("Name");

                    b.Property<int>("ResultStatus");

                    b.HasKey("Id", "SheetId");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
